Ensure that libraries can be used by base contracts
If a base contract uses a library which was not references by the concrete
library, then this cause a panic.

thread 'main' panicked at 'no entry found for key', src/codegen/expression.rs:1076:30

Signed-off-by: Sean Young <sean@mess.org>